name: issues
on:
  issues:
    types: [opened]
jobs:
 output-info:
    runs-on: ubuntu-latest
    steps:
      - name: output issue info
        run: |
          echo "Issue opened on ${{ github.event.issue.created_at }} by ${{ github.event.issue.user.login }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue url: ${{ github.event.issue.html_url }}"
          echo "Issue labels: ${{ github.event.issue.labels }}"
 