name: Use Secrets in Workflow

on:
  workflow_dispatch:
  push:
    branches:
      -*

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print a Secret
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "The API key is: $API_KEY"
      
      
    
